
        <div class="row">
            <div class="col-md-12">

                <h1>Standalone</h1>

                <div class="panel panel-default">

                    <div class="panel-heading clearfix">
                        <?php if ($this->allowCreateItem) : ?>
                        <a class="btn btn-default pull-left" href="<?php echo $this->url('item', ['action' => 'create'], ['query' => ['from' => 'standalone', 'provisionalTo' => 'Standalone']]); ?>">Create new</a>
                        <?php endif; ?>
                    </div>

                    <table class="table">
                        <tbody>

                            <?php if ($this->standaloneItems) : ?>
                                <?php echo $this->partialLoop('boxspaced/cms-standalone-module/standalone/standalone-item.phtml', $this->standaloneItems) ?>
                            <?php else : ?>
                                <tr class="odd"><td width="100%">Empty result set</td><td colspan="7">&nbsp;</td></tr>
                            <?php endif; ?>

                        </tbody>
                    </table>

                </div>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml'
                ); ?>

            </div>
        </div>
