
        <div class="row">
            <div class="col-md-12">

                <h1>Index of: standalone content</h1>

                <?php if ($this->allowCreateItem) : ?>
                <div class="actions">
                    <img src="/images/icons/add.png" alt="Add icon" />
                    <a class="link-button" href="<?php echo $this->url('item', ['action' => 'create'], ['query' => ['from' => 'standalone', 'provisionalTo' => 'Standalone']]); ?>">Create new</a>
                </div>
                <?php endif; ?>

                <table class="table">

                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th colspan="7">Actions</th>
                        </tr>
                    </thead>

                    <tbody>

                        <?php if ($this->standaloneItems) : ?>
                            <?php echo $this->partialLoop('boxspaced/cms-standalone-module/standalone/standalone-item.phtml', $this->standaloneItems) ?>
                        <?php else : ?>
                            <tr class="odd"><td width="100%">Empty result set</td><td colspan="7">&nbsp;</td></tr>
                        <?php endif; ?>

                    </tbody>
                </table>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml'
                ); ?>

            </div>
        </div>
